# Generated by Django 4.1.1 on 2022-12-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default=1, upload_to='static/images/user-profile'),
            preserve_default=False,
        ),
    ]
