# Generated by Django 4.1.4 on 2022-12-13 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LanguageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('published_on', models.DateTimeField(auto_now_add=True)),
                ('reading_time', models.IntegerField(default=5)),
                ('slug', models.CharField(blank=True, max_length=150)),
                ('thubmnail', models.ImageField(blank=True, upload_to='images/news')),
                ('title', models.CharField(max_length=150)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.categorymodel')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.languagemodel')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.regionmodel')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.sectionmodel')),
            ],
        ),
    ]
