# Generated by Django 4.1.4 on 2022-12-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodel',
            name='reading_time',
            field=models.IntegerField(default=5),
        ),
    ]
