# Generated by Django 4.1.4 on 2022-12-13 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newsmodel_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsmodel',
            old_name='thubmnail',
            new_name='thumbnail',
        ),
    ]
