# Generated by Django 4.1.4 on 2022-12-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newsmodel_reading_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='category',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='languagemodel',
            name='language',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='region',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='sectionmodel',
            name='section',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
