# Generated by Django 4.1.4 on 2022-12-14 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_rename_thubmnail_newsmodel_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='href',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='ne',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
