# Generated by Django 4.1.1 on 2022-12-07 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='poster',
            field=models.ImageField(upload_to='media/images/post'),
        ),
    ]
